package week1.day1.exceptions;

public class ExceptionsPractice {

	public static int divide(int x, int y) {
		return x / y;
	}
	
	public static void main(String[] args) {
		// try/catch block
		try {
			// Code that "could" break goes here
		}
		int x = divide(5, 0);
		System.out.println("Program finished");
	}
}
